[buildPlans.raftariosevka]
family = "raftariosevka"
spacing = "term"
serifs = "sans"

[buildPlans.raftariosevka.ligations]
enables = ["center-ops", "arrow", "trig", "ineq", "ltgt-diamond", "kern-dotty", "llgg"]

[buildPlans.raftariosevka.variants.design]
capital-a = "straight"
capital-b = "standard"
capital-c = "unilateral-inward-serifed"
capital-d = "standard"
capital-e = "standard"
capital-f = "standard"
capital-g = "toothless-corner-inward-serifed-hooked"
capital-h = "standard"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight"
capital-l = "standard"
capital-m = "hanging"
capital-n = "standard"
capital-p = "closed"
capital-q = "curly-tailed"
capital-r = "straight"
capital-s = "unilateral-inward-serifed"
capital-t = "standard"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight"
capital-x = "straight"
capital-y = "straight"
capital-z = "top-motion-serifed"
a = "single-storey-earless-corner"
b = "toothless-corner"
c = "serifless"
d = "toothless-corner"
e = "flat-crossbar"
f = "serifless"
g = "earless-corner"
h = "straight"
i = "hooky"
j = "serifed"
k = "straight"
l = "tailed"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
s = "serifless"
t = "flat-hook"
u = "toothless-corner"
v = "straight"
w = "straight-flat-top"
x = "straight"
y = "straight"
z = "standard"
lambda = "straight"
zero = "slashed"
one = "nobase"
two = "curly-neck"
three = "twoarcs"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "noserif"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "low"
underscore = "high"
caret = "low"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "et-toothless-corner"
at = "threefold"
dollar = "open"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
